# Generated by Django 3.2.10 on 2022-06-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_follow_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
